name: Windows Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOURCE_DIR:   ${{ github.workspace }}\platform
  ARTIFACT:     ${{ github.workspace }}\platform\build\release\MLVApp.Win64.zip

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      run: |
           choco install qt5-default
              
    - name: Create build directory
      run:  mkdir ${{ env.SOURCE_DIR }}\build

    - name: Build
      working-directory: ${{ env.SOURCE_DIR }}\build
      run:  |
            C:\Qt\5.15.2\mingw81_64\bin\qmake.exe -r ${{ env.SOURCE_DIR }}/qt/MLVApp.pro
            make.exe
            dir
            cd release
            C:\Qt\5.15.2\mingw81_64\bin\windeployqt MLVApp.exe
            dir

    - name: Decompress FFMPEG
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ${{ env.SOURCE_DIR }}\qt\FFmpeg\ffmpegWin64.zip -d ${{ env.SOURCE_DIR }}\build\release

    - name: Decompress RAW2MLV
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ${{ env.SOURCE_DIR }}\qt\raw2mlv\raw2mlvWin64.zip -d ${{ env.SOURCE_DIR }}\build\release

    - name: Zip build
      working-directory: ${{ env.SOURCE_DIR }}\build\release
      run:  |
            7z a MLVApp.Win64.zip ${{ env.SOURCE_DIR }}\build\release* -r

    - name: Save build artifact
      uses: actions/upload-artifact@master
      with:
        name: MLVApp Windows
        path: ${{ env.ARTIFACT }}
